---
abstract: 'pure Perl anagram finder'
author:
  - 'David F. Houghton <dfhoughton@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Exception: '0'
  Test::More: '0.88'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-Anagrams
no_index: {}
requires:
  List::MoreUtils: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
version: '0.012'
